project:
  type: website

website:
  title: "Nothing to see here"
  navbar:
    left:
      - index.qmd
      - about.qmd
  
execute: 
  freeze: true

date-format: "D MMMM YYYY"

format:
  html: default
